name: NPM Publish@beta

on:
  push:
    branches:
      - main

jobs:
  check_pkg_version:
    runs-on: ubuntu-latest

    # outputs:
    #   doPublish:
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
    - name: "checkout"
      uses: actions/checkout@v2

    - name: "setup node"
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # - run: SHOULD_PUBLISH=0

    - run: npm i semver-compare-cli

    # - run: PKG_VERSION_PUBLISHED=`npm view algonaut.js version`
    # - run: echo $PKG_VERSION_PUBLISHED
    # - run: PKG_VERSION_LOCAL=`cat package.json | jq -r '.version'`
    # - run: echo $PKG_VERSION_LOCAL

    # - run: |
    #     SOME_ENV_VAR="this is an env var!"
    #     echo '::echo::on'
    #     echo $SOME_ENV_VAR
    #     echo "$SOME_ENV_VAR"
    #     echo "::set-output name=action_echo::$SOME_ENV_VAR"
    #     echo "it is... ${{env.action_echo}}"
    # - run: echo "::set-output name=packageJson::$PKG_VERSION_LOCAL"

    - name: step1
      run: |
        echo '::echo::on'
        SHOULD_PUBLISH=0
        PKG_VERSION_PUBLISHED=`npm view algonaut.js version`
        echo $PKG_VERSION_PUBLISHED
        PKG_VERSION_LOCAL=`cat package.json | jq -r '.version'`
        echo $PKG_VERSION_LOCAL
        npx semver-compare $PKG_VERSION_LOCAL gt $PKG_VERSION_PUBLISHED && SHOULD_PUBLISH=1
        echo "publish?"
        echo $SHOULD_PUBLISH
        if [[ $SHOULD_PUBLISH ]] ; then echo "will npm publish beta"; else echo "no npm publish needed" ; fi
        echo "::set-output name=test::$SHOULD_PUBLISH"
        echo "DO_PUBLISH=$SHOULD_PUBLISH" >> $GITHUB_ENV

    # - run: npx semver-compare $PKG_VERSION_LOCAL gt $PKG_VERSION_PUBLISHED && SHOULD_PUBLISH=1

    # - run: if [[ $PKG_VERSION_LOCAL > $PKG_VERSION_PUBLISHED ]] ; then SHOULD_PUBLISH=1; else SHOULD_PUBLISH=0 ; fi
    # - run: echo $SHOULD_PUBLISH

    # - name: "should action npm publish?"
    #   run: if [[ $SHOULD_PUBLISH ]] ; then echo "will npm publish@beta"; else echo "no npm publish needed" ; fi
    # - run: echo "DO_PUBLISH=$SHOULD_PUBLISH" >> $GITHUB_ENV

  publish:
    needs: [ check_pkg_version ]
    if: ${{ needs.check_pkg_version.outputs.output1 == 1 }}
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
          # creates an .npmrc

      - name: "install"
        run: npm ci

      - name: "build"
        run: npm run build

      - name: "publish"
        run: npm publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}